### PR TITLE
Add Modbus command $11 for getting a device ID.

### PR DESCRIPTION
**Pull request by LongDirtyAnimAlf**

### CODE REVIEW

**Comment by LongDirtyAnimAlf** [comment]
I have only done this for RTU.
But TCP should be easily adapted.

**Comment by fluisgirardi** [comment]
I'm trying to understand why you are using the Registers are to a modbus function that wasn't designed as data exchange function

**Comment by fluisgirardi** [comment]
About replicate these changes to TCP: function 0x11 is RTU exclusive or I'm wrong?

**Comment by fluisgirardi** [comment]
How the reply to 0x11 request is limited to 255 bytes, I think that's better create a new PModbusPLC[plc]._0x11area with fixed size (256 bytes) and fixed initial address (always from 0)  instead using Register area. What do you think?

**Comment by LongDirtyAnimAlf** [comment]
You are the expert.
I just tried to implement this function without deep knowledge of your PascalScada.
So I will fully agree with you about a better method of implementing this !
Thanks for looking into this. And thanks for implementing in a more suitable manner.

**Pull request merged**
